import json

# Dicionário com os códigos e suas descrições
descricao_eventos = {
    
    "101": "101 - Inscrição de primeiro estabelecimento",
    "102": "102 - Inscrição dos demais estabelecimentos",
    "103": "103 - Inscrição de estabelecimento filial de empresa brasileira no exterior",
    "105": "105 - Inscrição de embaixada/consulado/representações do governo no exterior",
    "106": "106 - Inscrição de missões dipl./repart. consul./repres. de órgãos internacionais",
    "107": "107 - Inscrição de Pessoa Jurídica domiciliada no exterior",
    "109": "109 - Inscrição de incorporação imobiliária (patrimônio de afetação)",
    "110": "110 - Inscrição de Produtor Rural (Primeiro Estabelecimento)",
    "111": "111 - Inscrição de Produtor Rural (Demais Estabelecimentos)",
    "202": "202 - Alteração da pessoa física responsável perante o CNPJ",
    "203": "203 - Exclusão do título do estabelecimento (nome de fantasia)",
    "204": "204 - Cisão parcial (específico para a sucedida)",
    "206": "206 - Desclassificação como estabelecimento unificador",
    "209": "209 - Alteração de endereço entre municípios dentro do mesmo estado",
    "210": "210 - Alteração de endereço entre estados",
    "211": "211 - Alteração de endereço dentro do mesmo município",
    "214": "214 - Alteração de telefone (DDD/telefone)",
    "215": "215 - Exclusão de telefone (DDD/telefone)",
    "216": "216 - Alteração de fax (DDD/fax)",
    "217": "217 - Exclusão de fax (DDD/fax)",
    "218": "218 - Alteração de correio eletrônico",
    "219": "219 - Exclusão de correio eletrônico",
    "220": "220 - Alteração do nome empresarial (firma ou denominação)",
    "221": "221 - Alteração do título do estabelecimento (nome de fantasia)",
    "222": "222 - Enquadramento / Reenquadramento / Desenquadramento de ME/EPP",
    "224": "224 - Alteração do contabilista responsável pela organização contábil perante o CRC",
    "225": "225 - Alteração da natureza jurídica",
    "230": "230 - Alteração da qualificação da pessoa física responsável perante o CNPJ",
    "232": "232 - Alteração do contabilista ou da empresa de contabilidade",
    "233": "233 - Exclusão do contabilista ou da empresa de contabilidade",
    "235": "235 - Alteração do Administrador de Empresas (Fundos/Clubes e Equiparadas)",
    "237": "237 - Indicação de Preposto",
    "238": "238 - Substituição de Preposto",
    "239": "239 - Exclusão do Preposto",
    "240": "240 - Renúncia do Preposto",
    "241": "241 - Equiparação, por opção, a estabelecimento industrial",
    "242": "242 - Desistência da equiparação, por opção, a estabelecimento industrial",
    "243": "243 - Alteração de endereço de Pessoa Jurídica domiciliada no exterior",
    "244": "244 - Alteração de atividades econômicas (principal e secundárias)",
    "245": "245 - Alteração de NIRE",
    "246": "246 - Indicação de estabelecimento matriz",
    "247": "247 - Alteração de capital social",
    "248": "248 - Alteração do tipo de unidade",
    "249": "249 - Alteração da forma de atuação",
    "250": "250 - Alteração do vínculo com o imóvel",
    "251": "251 - Alteração da data de validade da inscrição",
    "252": "252 - Alteração do NIRF",
    "253": "253 - Alteração do proprietário",
    "254": "254 - Alteração do nome empresarial (específico para Produtor Rural)",
    "255": "255 - Exclusão de NIRE",
    "256": "256 - Alteração da Inscrição Estadual Anterior",
    "257": "257 - Alteração do número de registro no órgão competente",
    "258": "258 - Atualização de dados anteriores do contribuinte",
    "260": "260 - Alteração/Inclusão de Ente Federativo Responsável",
    "261": "261 - Exclusão do número de registro no órgão competente",
    "262": "262 - Alteração da Dependência Orçamentária",
    "263": "263 - Alteração do Responsável - Produtor Rural",
    "264": "264 - Alteração de Tipo de Produtor Rural (Individual ou Sociedade)",
    "301": "301 - Inclusão no Simples Federal por opção da empresa",
    "302": "302 - Exclusão do Simples Federal por Opção da Empresa",
    "303": "303 - Exclusão Simples Federal por débito p/ com Fazenda Nacional ou Previdência Social",
    "304": "304 - Exclusão do Simples Federal por ultrapassar os limites de receita bruta",
    "305": "305 - Exclusão do Simples Federal por transformação para a forma de sociedade por ações",
    "306": "306 - Exclusão do Simples Federal por exercício de atividade econômica vedada",
    "307": "307 - Exclusão do Simples Federal por ingresso de sócio estrangeiro residente no exterior",
    "308": "308 - Exclusão Simples Federal por transf. filial,suc.,ag. ou repres. de PJ com sede no exterior",
    "309": "309 - Exclusão do Simples Federal por participação no capital de outra pessoa jurídica",
    "310": "310 - Exclusão Simples Federal por exist. titular/sócio realize gastos incomp. com rendimentos declarados",
    "311": "311 - Exclusão Simples Federal por participação do titular ou sócio no capital de outra empresa",
    "312": "312 - Exclusão Simples Federal por participação de outra pessoa jurídica no capital da empresa",
    "313": "313 - Exclusão do Simples Federal por receita de venda de bens importados superior ao limite",
    "314": "314 - Exclusão do Simples Federal por prática de embaraço ou resistência à fiscalização",
    "315": "315 - Exclusão do Simples Federal retroativa à data da opção / abertura",
    "316": "316 - Alteração de tributos do Simples Federal",
    "317": "317 - Desfaz exclusão indevida",
    "318": "318 - Desfaz inclusão indevida",
    "319": "319 - Inclusão no Simples Federal por decisão administrativa",
    "320": "320 - Inclusão no Simples Federal por mandado judicial",
    "321": "321 - Exclusão do Simples Federal por decisão administrativa",
    "322": "322 - Exclusão Simples Federal empresa resultante cisão ou qualquer forma de desmembramento",
    "325": "325 - Exclusão do Simples Federal por industrializar bebidas ou cigarros",
    "326": "326 - Alteração do Porte da Empresa",
    "327": "327 - Evento de alteração de período do Simples Nacional",
    "403": "403 - Início de liquidação",
    "405": "405 - Decretação de falência",
    "406": "406 - Reabilitação de falência",
    "407": "407 - Espólio de Empresário/Empresa Individual Imobiliária",
    "408": "408 - Término de liquidação",
    "410": "410 - Intervenção",
    "411": "411 - Término de intervenção",
    "412": "412 - Interrupção temporária de atividades",
    "413": "413 - Reinício das atividades interrompidas temporariamente",
    "414": "414 - Restabelecimento de Inscrição da Entidade",
    "415": "415 - Restabelecimento de Inscrição de Filial",
    "416": "416 - Início de Liquidação Judicial",
    "417": "417 - Início de Liquidação Extrajudicial",
    "418": "418 - Recuperação Judicial",
    "419": "419 - Encerramento de Recuperação Judicial",
    "510": "510 - Extinção por determinação judicial",
    "514": "514 - Anulação de Inscrição indevida",
    "516": "516 - Anulação por Vício",
    "517": "517 - Pedido de baixa",
    "518": "518 - Baixa - Omissão Contumaz",
    "519": "519 - Baixa - Inexistência de Fato",
    "520": "520 - Baixa - Inaptidão",
    "521": "521 - Baixa - Registro Cancelado",
    "522": "522 - Baixa - Inaptidão;",
    "523": "523 - Baixa - Registro Cancelado;",
    "601": "601 - Inscrição no Estado;",
    "602": "602 - Inscrição de Substituto Tributário no Estado;",
    "603": "603 - Reativação da inscrição no Estado;",
    "604": "604 - Pedido de baixa exclusivamente no Estado;",
    "605": "605 - Alteração do endereço de correspondência;",
    "606": "606 - Inscrição no Estado para estabelecimento que está localizado em outro Estado, exceto Subst. Trib.;",
    "607": "607 - Pedido de baixa de substituto tributário;",
    "608": "608 - Reativação de Substituto Tributário no Estado;",
    "611": "611 - Alteração do regime de apuração no Estado;",
    "612": "612 - Alteração de dados da licença ambiental;",
    "613": "613 - Alteração da Condição de Substituto Tributário;",
    "621": "621 - Alteração de condição / regime de apuração;",
    "622": "622 - Alteração do número COELBA;",
    "623": "623 - Alteração de valores de compras/vendas;",
    "624": "624 - Alteração da localização;",
    "625": "625 - Opção ou exclusão da inscrição única;",
    "626": "626 - Inclusão de estabelecimento da inscrição única;",
    "627": "627 - Exclusão de estabelecimento da inscrição única;",
    "628": "628 - Alteração do Tipo de Contribuinte;",
    "629": "629 - Alteração da opção por livros/documentos eletrônicos;",
    "630": "630 - Alteração da permanência de livros fiscais;",
    "632": "632 - Alteração do tipo de convênio / protocolo de substituição tributária;",
    "633": "633 - Alteração do Procurador no Estado;",
    "634": "634 - Alteração de correio eletrônico da pessoa física responsável perante o CNPJ;",
    "635": "635 - Reativação de Substituto Tributário no Estado;",
    "801": "801 - Inscrição no município;",
    "802": "802 - Inscrição municipal vinculada a CNPJ já cadastrado para outro estabelecimento;",
    "803": "803 - Inscrição para estabelecimento sediado em outro município;",
    "804": "804 - Pedido de baixa exclusivamente no município;",
    "805": "805 - Correção do número de inscrição imobiliária;",
    "806": "806 - Alteração de área;",
    "807": "807 - Desdobramento de atividades econômicas (principal e secundárias);",
    "808": "808 - Renovação do TVL (Alvará);",
    "809": "809 - Informação de código de anúncio;",
    "810": "810 - Inscrição no município de São Paulo para estabelecimento sediado em outro município;",
    "811": "811 - Informação do Número CCM Centralizador;",
    "812": "812 - Alteração do endereço do estabelecimento vinculado;",
    "813": "813 - Alteração do telefone do estabelecimento vinculado;",
    "814": "814 - Alteração do regime de tributação;",
    "815": "815 - Pedido de baixa de estabelecimento sediado em outro município;",
    "901": "901 - Inclusão de CNPJ - matriz ou filial;",
    "902": "902 - Inscrição de estabelecimento por determinação judicial;",
    "903": "903 - Restabelecimento de situação cadastral para ativa regular;",
    "906": "906 - Anulação por Multiplicidade de Inscrição;",
    "909": "909 - Restauração da Situação Cadastral Anterior;",
    "910": "910 - Alteração de Data de Abertura;",
    "912": "912 - Suspensão - Baixa Recepcionada (Em Análise);",
    "913": "913 - Suspensão - Baixa Indeferida;",
    "915": "915 - Suspensão - Inexistência de Fato;",
    "916": "916 - Inaptidão - Inexistência de Fato;",
    "917": "917 - Desfaz Suspensa - Inexistente de Fato;",
    "918": "918 - Desfaz Inapta - Inexistente de Fato;",
    "919": "919 - Desfaz baixa;",
    "921": "921 - Alteração de Motivo de Inaptidão;",
    "922": "922 - Desfaz Inaptidão por Determinação Judicial;",
    "923": "923 - Alteração de Data de Publicação / Data de Efeito;",
    "924": "924 - Correção da data de baixa;",
    "925": "925 - Alteração do indicador de interesse DCTF/ADUANA;",
    "926": "926 - Desfaz cisão parcial;",
    "927": "927 - Suspensão - Indício de Interposição Fraudulenta;",
    "928": "928 - Suspensão - Falta de Pluralidade de Sócios;",
    "929": "929 - Correção da data de Responsabilidade;",
    "938": "938 - Suspensão - Determinação Judicial;",
    "939": "939 - Inaptidão - Omissão de Declarações;",
    "940": "940 - Inaptidão - Localização Desconhecida;",
    "941": "941 - Substituição/Eliminação do Registro de Responsabilidade;"

}

def adicionar_descricao(arquivo_json):
    
    with open(arquivo_json, 'r', encoding='utf-8') as f:
        dados = json.load(f)
    for evento in dados["eventos"]:
        codigo = evento["evento"]
        evento["descricao"] = descricao_eventos.get(codigo, "Descrição não encontrada")
    for combinacao in dados.get("combinacoes", []):
        codigos = combinacao["combinacao"].split(",")
        descricoes = [descricao_eventos.get(codigo, "Descrição não encontrada") for codigo in codigos]
        combinacao["descricao"] = " e ".join(descricoes)
    with open(arquivo_json, 'w', encoding='utf-8') as f:
        json.dump(dados, f, ensure_ascii=False, indent=2)


adicionar_descricao("C:/Users/fcristiano/Documents/DTO/MeuProjetoSql/XmlRFBS17 - Eventos.json")
